version: '3.5'

services:
  backend1:
    image: anthos-poc-app-backend1
    container_name: anthos-poc-app-backend1
    restart: always
    depends_on:
      - backend2
    networks:
      - backend
    environment:
      PORT: 3000
      GRPC_URL: backend2:50051

  backend2:
    image: anthos-poc-app-backend2
    container_name: anthos-poc-app-backend2
    restart: always
    networks:
      - backend
    environment:
      PORT: 3000
      GRPC_PORT: 50051

networks:
  backend:
    name: anthos-poc-app-backend
    driver: bridge

